logging:
  level:
    org.springframework: INFO
    de.eblaas.products: DEBUG

spring:
  profiles:
    active: dev
  main:
    banner-mode: "off"
---
spring:
  profiles: dev
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 4
        generate_statistics: false
        search:
          default:
            indexBase: data/index
---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://postgresql-service:5432/postgres
    username: ''
    password: ''
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        search:
          default:
            indexmanager: elasticsearch
            elasticsearch:
              host: http://elasticsearc-service:9200
              index_schema_management_strategy: create
              required_index_status: yellow
